const APIS = {
  Address: "/address/random_address",
  Appliance: "/appliance/random_appliance",
  Bank: "/bank/random_bank",
  Beer: "/beer/random_beer",
  Blood: "/blood/random_blood",
  "Business Credit Card ": "/business_credit_card/random_card",
  Cannabis: "/cannabis/random_cannabis",
  Code: "/code/random_code",
  Coffee: "/coffee/random_coffee",
  Commerce: "/commerce/random_commerce",
  Company: "/company/random_company",
  Computer: "/computer/random_computer",
  Crypto: "/crypto/random_crypto",
  CryptoCoin: "/crypto_coin/random_crypto_coin",
  Color: "/color/random_color",
  Dessert: "/dessert/random_dessert",
  Device: "/device/random_device",
  Food: "/food/random_food",
  Name: "/name/random_name",
  Hipster: "/hipster/random_hipster_stuff",
  Invoice: "/invoice/random_invoice",
  Users: "/users/random_user",
  Stripe: "/stripe/random_stripe",
  Subscrpiption: "/subscription/random_subscription",
  Vehicle: "/vehicle/random_vehicle",
  "ID Number": "/id_number/random_id_number",
  "Internet Stuff": "/internet_stuff/random_internet_stuff",
  "Lorem Ipsum": "/lorem_ipsum/random_lorem_ipsum",
  "Lorem Flickr": "/lorem_flickr/random_lorem_flickr",
  "Lorem Pixel": "/lorem_pixel/random_lorem_pixel",
  Nation: "/nation/random_nation",
  Number: "/number/random_number",
  "Phone Number": "/phone_number/random_phone_number",
  Placeholdit: "/placeholdit/random_placeholdit",
  Restaurant: "/restaurant/random_restaurant",
};
exports.APIS = APIS;
