const healthData = [
  "E. Fougera & Co. a division of Fougera Pharmaceuticals Inc.",
  "Unique Holding Group Inc",
  "Deb USA",
  "Energique",
  "Lifetech Resources",
  "Valu Merchandisers",
  "Nelco Laboratories",
  "Stiefel Laboratories Inc",
  "Allergan",
  "Aurobindo Pharma Limited",
  "HandsFree",
  "Washington Homeopathic Products",
  "Bedford Laboratories",
  "Apotex Corp",
  "Ranbaxy Pharmaceuticals Inc.",
  "Mylan Pharmaceuticals Inc.",
  "Sun Pharma Global FZE",
  "Golden State Medical Supply",
  "THE KROGER CO",
  "CCA Industries",
  "Pierre Fabre Dermo Cosmetique",
  "Sam's West Inc",
  "CVS Pharmacy",
  "REMEDYREPACK INC.",
  "Ranbaxy Laboratories Inc.",
  "Bryant Ranch Prepack",
  "Nelco Laboratories",
  "Nelco Laboratories",
  "Aidarex Pharmaceuticals LLC",
  "Dolgencorp",
  "McKesson",
  "Bausch & Lomb Incorporated",
  "Genzyme Corporation",
  "HOMEOLAB USA INC",
  "Onpointm",
  "SJ Creations",
  "H.J. Harkins Company",
  "Dolgencorp",
  "Johnson & Johnson Healthcare Products",
  "Actavis Elizabeth LLC",
  "Arbor Pharmaceuticals",
  "Camber Pharmaceuticals",
  "REMEDYREPACK INC.",
  "L'Oreal USA Products Inc",
  "Hospira",
  "Allermed Laboratories",
  "Medicis Pharmaceutical Corp",
  "Solco Healthcare US LLC",
  "Spartan Chemical Company",
  "Uriel Pharmacy Inc.",
  "TYA Pharmaceuticals",
  "Mylan Pharmaceuticals Inc.",
  "Best Accessory Group",
  "Allermed Laboratories",
  "Avion Pharmaceuticals",
  "Lake Erie Medical DBA Quality Care Products LLC",
  "Roerig",
  "Walgreen Co",
  "Nelco Laboratories",
  "Cardinal Health",
  "Yein Trading & Global Co.",
  "Pfizer Laboratories Div Pfizer Inc",
  "Torrent Pharmaceuticals Limited",
  "Newton Laboratories",
  "Kroger Company",
  "Sanofi Pasteur Inc.",
  "Bryant Ranch Prepack",
  "Lupin Pharmaceuticals",
  "Bryant Ranch Prepack",
  "Nelco Laboratories",
  "Publix Super Markets Inc",
  "STAT RX USA LLC",
  "APHENA PHARMA SOLUTIONS - TENNESSEE",
  "Keltman Pharmaceuticals Inc.",
  "Actavis Pharma",
  "Dental Technologies",
  "APOLLO HEALTH AND BEAUTY CARE",
  "PD-Rx Pharmaceuticals",
  "Accra-Pac",
  "Hospira",
  "Apotex Corp",
  "Merck Sharp & Dohme Corp.",
  "ALK-Abello",
  "Cardinal Health",
  "Antigen Laboratories",
  "Amphastar Pharmaceuticals",
  "McKesson",
  "EQUATE (Walmart Stores",
  "Sagent Pharmaceuticals",
  "KMART CORPORATION",
  "Bryant Ranch Prepack",
  "Nova Homeopathic Therapeutics",
  "Airgas Merchant Gases",
  "Betco Corporation",
  "Mylan Pharmaceuticals Inc.",
  "Apotheca Company",
  "Wal-Mart Stores Inc",
  "ALK-Abello",
  "LVMH Fragrance Brands",
  "Paddock Laboratories",
  "Camber Pharmaceuticals",
  "Topco Associates LLC",
  "Meijer Distribution Inc",
  "S.I.P.R.E.S. SRL",
  "Eon Labs, Inc.",
  "Meijer",
  "Natural Health Supply",
  "Physicians Total Care, Inc.",
  "Clinical Solutions Wholesale",
  "Celgene Corporation",
  "Johnson & Johnson Consumer Products Company, Division of Johnson & Johnson Consumer Companies, Inc.",
  "Qualitest Pharmaceuticals, Inc,",
  "LG Household and Healthcare, Inc.",
  "Aphena Pharma Solutions - Tennessee, Inc.",
  "H E B",
  "Major Pharmaceuticals",
  "Walgreen Co",
  "Liberty Pharmaceuticals, Inc.",
  "REMEDYREPACK INC.",
  "Aurobindo Pharma Limited",
  "REMEDYREPACK INC.",
  "REMEDYREPACK INC.",
  "Dispensing Solutions, Inc.",
  "Eon Labs, Inc.",
  "APP Pharmaceuticals, LLC",
  "Tec Laboratories, Inc.",
  "Teva Pharmaceuticals USA Inc",
  "Teva Women's Health, Inc.",
  "American Health Packaging",
  "Health Complex Medical Inc",
  "Pfizer Laboratories Div Pfizer Inc",
  "Lake Erie Medical DBA Quality Care Products LLC",
  "Actavis Inc.",
  "Apotheca Company",
  "Babor Cosmetics America, Corp",
  "Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC",
  "Mylan Pharmaceuticals Inc.",
  "OCuSOFT, Inc.",
  "Elizabeth Arden, Inc",
  "Avon Products, Inc.",
  "OHTA'S ISAN CO., LTD",
  "Ventura Corporation LTD",
  "Harmon Stores Inc.",
  "Ventura Corporation LTD.",
  "Actavis Pharma, Inc.",
  "Lake Welding Supply Company",
  "ENCHANTE ACCESSORIES INC.",
  "Qualitest Pharmaceuticals",
  "Noxell",
  "Wal-Mart Stores Inc",
  "Cardinal Health",
  "Uriel Pharmacy Inc.",
  "Rebel Distributors Corp",
  "E. Fougera & Co. a division of Fougera Pharmaceuticals Inc.",
  "Sanum Kehlbeck GmbH & Co. KG",
  "Haemonetics Manufacturing Inc",
  "Physicians Total Care, Inc.",
  "Atlantic Biologicals Corps",
  "SPAI-SONS PHARAMCUETICAL INTERNATIONAL COSMETICS",
  "Newton Laboratories, Inc.",
  "AMOREPACIFIC",
  "NATURE REPUBLIC CO., LTD.",
  "Wal-Mart Stores Inc",
  "Warner Chilcott (US), LLC",
  "GUILIN TIANHE PHARMACEUTICAL CO LTD",
  "West-Ward Pharmaceutical Corp",
  "Nelco Laboratories, Inc.",
  "Jafra Cosmetics International Inc",
  "E. Fougera & Co. a division of Fougera Pharmaceuticals Inc.",
  "Walgreens",
  "Bryant Ranch Prepack",
  "Nelco Laboratories, Inc.",
  "REMEDYREPACK INC.",
  "Roxane Laboratories, Inc",
  "Meijer Distribution, Inc",
  "Dukal Corporation",
  "Coty US LLC",
  "MULTALER ET CIE S.A.S.",
  "Teva Pharmaceuticals USA Inc",
  "Prasco LLC",
  "MallyGirl, LLC",
  "Quality Home Healthcare, Inc.",
  "Lupin Pharmaceuticals, Inc.",
  "Vitality Works, Inc.",
  "Nelco Laboratories, Inc.",
  "Caraco Pharmaceutical Laboratories, Ltd.",
  "Universal Cosmetic Co., Ltd",
  "Genzyme Corporation",
  "Dynarex Corporation",
  "Topco Associates LLC",
  "Pronova Corporation",
  "Mason Chemical Company",
  "Roxane Laboratories, Inc",
  "Rebel Distributors Corp",
  "TYA Pharmaceuticals",
  "Cadila Healthcare Limited",
  "Aurobindo Pharma Limited",
  "Heritage Pharmaceuticals Inc.",
  "Family Dollar",
  "Paddock Laboratories",
  "Ramipril",
  "Topcare Milk of Magnesia",
  "ibuprofen",
  "Biodynamic Skin",
  "Benazepril Hydrochloride and Hydrochlorothiazide",
  "Antiseptic Rinse",
  "Dry Cough Diarrhea",
  "Timolol Maleate",
  "Carvedilol",
  "Thalomid",
  "Aveeno Active Naturals Ultra Calming Daily Moisturizer",
  "Metaproterenol Sulfate",
  "ISA KNOX 365 BB SUNSCREEN Broad Spectrum SPF 40, PA",
  "Lithium Carbonate",
  "WHITE LAVENDER AND MINT ANTIBACTERIAL MOISTURIZING HAND SP",
  "Extra Strength Mapap PM",
  "Petroleum Skin Protectant",
  "Cephalexin",
  "Gabapentin",
  "Modafinil",
  "Prednisone",
  "Metronidazole",
  "Tamiflu",
  "Metolazone",
  "Vancomycin Hydrochloride",
  "Licefreee Everyday",
  "Doxazosin",
  "Urecholine",
  "Divalproex Sodium",
  "Oxygen",
  "Doxorubicin Hydrochloride",
  "Triamterene and Hydrochlorothiazide",
  "Gabapentin",
  "Pre Post Surgery",
  "BABOR Stop Cellulite",
  "SERTRALINE HYDROCHLORIDE",
  "Bisoprolol Fumarate and Hydrochlorothiazide",
  "Tears Again",
  "Intervene Makeup Broad Spectrum Sunscreen SPF 15 Soft Cognac",
  "Clearskin",
  "Ohtas Isan Antacid",
  "ESIKA 3-IN-1 PRO MAKE UP FOUNDATION SPF 20 BASE DE MAQUILLAJE PARA ROSTRO 3-EN-1 PRO FPS 20",
  "harmon face values omeprazole",
  "LBEL HYDRATESS",
  "risedronate sodium",
  "Oxygen",
  "Body Luxuries Cherry Blossom Waterless Anti-bacterial Hand Sanitizer",
  "Prednisone",
  "Covergirl Queen Collection All Day Flawless 3in1 Foundation",
  "Sinus Congestion and Pain",
  "leader nite time cough",
  "Sarothamnus Aurum",
  "MAXALT",
  "Clobetasol Propionate",
  "Pleo Muc Ex",
  "LEUKOSEP - CPD Solution",
  "Valacyclovir Hydrochloride",
  "ELIXOPHYLLIN",
  "SPAI-SONS",
  "Appetite - Craving Control",
  "Sulwhasoo Lumitouch Base",
  "BERRY BABY LIP BALM VIOLET BERRY",
  "equate ibuprofen",
  "FEMCON Fe",
  "TIANHE GUBEN YAOSHEN TIE GAO",
  "NAPROXEN",
  "Sugar Maple",
  "Pure Porcelain Skin Defense Makeup SPF 15",
  "Diflorasone Diacetate",
  "NICOTINE",
  "ESZOPICLONE",
  "Sweet Gum",
  "Naproxen",
  "Dexamethasone",
  "Itchy Scalp",
  "Dukal Alcohol Prep Pad",
  "Sally Hansen Microwavable Eybrow, Face and Lip Wax Kit",
  "SPF 20 UVA/UVB",
  "Simvastatin",
  "leflunomide",
  "mally Poreless Perfection Glowing Foundation Medium",
  "Oxygen",
  "Irbesartan and Hydrochlorothiazide",
  "CL-N",
  "Rhodotorula mucilaginosa",
  "Metoprolol Tartrate",
  "MediSpa Sunblock",
  "Campath",
  "DYNAREX LAXATIVE",
  "topcare tussin CF",
  "MaxFe",
  "Nobac Plus AB-F E2",
  "Fluticasone Propionate",
  "Miconazole Nitrate",
  "Gabapentin",
  "Lamotrigine",
  "Lamotrigine",
  "Moexipril hydrochloride and hydrochlorothiazide",
  "Laxative for Women",
  "Ramipril",
  "Magnesium hydroxide",
  "Ibuprofen",
  "AVOBENZONE, OCTINOXATE",
  "Benazepril Hydrochloride and Hydrochlorothiazide",
  "Antiseptic",
  "SODIUM CATION",
  "Timolol Maleate",
  "Carvedilol",
  "Thalidomide",
  "Avobenzone, Octinoxate, and Octisalate",
  "Metaproterenol Sulfate",
  "TITANIUM DIOXIDE",
  "Lithium Carbonate",
  "TRICLOSAN",
  "ACETAMINOPHEN, DIPHENHYDRAMINE HYDROCHLORIDE",
  "White Petrolatum",
  "Cephalexin",
  "Gabapentin",
  "Modafinil",
  "Prednisone",
  "Metronidazole",
  "oseltamivir phosphate",
  "Metolazone",
  "VANCOMYCIN HYDROCHLORIDE",
  "natrum muriaticum",
  "Doxazosin Mesylate",
  "Bethanechol Chloride",
  "Divalproex Sodium",
  "Oxygen",
  "Doxorubicin Hydrochloride",
  "Triamterene and Hydrochlorothiazide",
  "Gabapentin",
  "Arnica montana, Bellis perennis, Bryonia, Calendula officinalis, Hypericum perforatum, Ledum palustre, Phosphorus, Pyrogenium, Rhus toxicodendron,",
  "Panthenol",
  "SERTRALINE HYDROCHLORIDE",
  "bisoprolol fumarate and hydrochlorothiazide",
  "Mineral oil, White petrolatum",
  "OCTINOXATE",
  "Salicylic Acid",
  "magnesium aluminosilicate, Calcium carbonate, sodium bicarbonate",
  "Octinoxate, Oxybenzone, and Titanium Dioxide",
  "Omeprazole",
  "Octinoxate and Oxybenzone",
  "risedronate sodium",
  "Oxygen",
  "ALCOHOL",
  "Prednisone",
  "Ensulizole",
  "Acetaminophen and Phenylephrine HCl",
  "Dextromethorphan HBr, Doxylamine succinate",
  "Sarothamnus Aurum",
  "rizatriptan benzoate",
  "clobetasol propionate",
  "Mucor racemosus immunoserum rabbit",
  "Citrate Phosphate Dextrose (CPD) Solution",
  "Valacyclovir Hydrochloride",
  "THEOPHYLLINE ANHYDROUS",
  "SULFUR",
  "Anacardium orientale, Antimon. crud., Arg. nit., Berber. vulg., Bryonia, Chelidonium majus, Digitalis, Graphites, Humulus, Iris versicolor, Kali carb., Lycopodium, Nat. carb. , Nat. sulphuricum, Nux vom., Pulsatilla, Rhus toxicodendron, Scutellaria lateriflora, Sepia, Stramonium, Chamomilla, Passiflora, Valeriana",
  "OCTINOXATE, TITANIUM DIOXIDE, and ZINC OXIDE",
  "OCTINOXATE, TITANIUM DIOXIDE",
  "Ibuprofen",
  "norethindrone and ethinyl estradiol, and ferrous fumarate",
  "MENTHOL",
  "naproxen sodium",
  "Sugar Maple",
  "Octinoxate, Octisalate, Oxybenzone",
  "Diflorasone Diacetate",
  "nicotine polacrilex",
  "ESZOPICLONE",
  "Sweet Gum",
  "Naproxen",
  "Dexamethasone",
  "Pyrithione zinc",
  "ISOPROPYL ALCOHOL",
  "Benzocaine",
  "HOMOSALATE, OCTINOXATE, OCTISALATE, OXYBENZONE, AVOBENZONE, OCTOCRYLENE",
  "Simvastatin",
  "leflunomide",
  "OCTINOXATE, OXYBENZONE, ZINC OXIDE, TITANIUM DIOXIDE",
  "Oxygen",
  "Irbesartan and Hydrochlorothiazide",
  "Emotional Health Booster",
  "Rhodotorula mucilaginosa",
  "Metoprolol tartrate",
  "zinc oxide",
  "ALEMTUZUMAB",
  "MINERAL OIL",
  "Dextromethorphan Hydrobromide, Guaifenesin, Phenylephrine Hydrochloride",
  "ascorbic acid, folic acid, vitamin b-12, biotin, iron, magnesium, zinc",
  "Benzalkonium Chloride",
  "Fluticasone Propionate",
  "miconazole nitrate",
  "Gabapentin",
  "Lamotrigine",
  "Lamotrigine",
  "Moexipril hydrochloride and hydrochlorothiazide",
  "Bisacodyl",
];

module.exports.healthData = healthData;
